### PR TITLE
Submission - AmitChigare

### PR DESCRIPTION
**Pull request by AmitChigare**
Submission for the Backend Internship Task.

### CODE REVIEW

**Comment by AmitChigare** [comment]
Submission for the Backend Internship Task.

**Comment by AmitChigare** [comment]
I have Made my submission. Please review my project. I have an issue of Github Classroom, not able to apply for the Octernships even though I had applied before my Github education account was verified and activated. Please look into this issue and help me out. I request to reach out to me for any kind of submission permission or detail.

**Comment by shuklaritvik06** [comment]
Hey 👋🏼 You do not have to make the public PR and please add venv folder to .gitignore file

**Comment by AmitChigare** [comment]
Created .gitignore file and included .venv too. Thank you.

**Pull request closed without merging**
