### PR TITLE
Vibhav shukla

### PR DESCRIPTION
**Pull request by vibhav10**
This is my submission for the Backend Internship Tasks in accordance with the instructions provided in the README file.

### CODE REVIEW

**Comment by shuklaritvik06** [comment]
Hey 👋🏼 You do not have to make the public PR

**Comment by vibhav10** [comment]
> Hey 👋🏼 You do not have to make the public PR

Hi Ritvik!
I couldn't find anything on my github classroom. So I decided to generate a pull request from a fork. 
Could you please share the correct procedure to make our submission? 
Thank you for your time and consideration.

**Comment by shuklaritvik06** [comment]
> > Hey 👋🏼 You do not have to make the public PR
> 
> Hi Ritvik! I couldn't find anything on my github classroom. So I decided to generate a pull request from a fork. Could you please share the correct procedure to make our submission? Thank you for your time and consideration.

You have to use the private repository only for the submission, no public PR need to be made for the submission

Steps to Follow

 - [x] Create a new branch dev from the main branch
 - [x] Commit your changes to the dev branch
 - [x] Now raise a PR from dev to main
 - [x] Merge that PR

 Your changes would be visible in Feedback#1 PR and there folks will review it

**Comment by vibhav10** [comment]
> > > Hey 👋🏼 You do not have to make the public PR
> > 
> > 
> > Hi Ritvik! I couldn't find anything on my github classroom. So I decided to generate a pull request from a fork. Could you please share the correct procedure to make our submission? Thank you for your time and consideration.
> 
> You have to use the private repository only for the submission, no public PR need to be made for the submission
> 
> Steps to Follow
> 
> * [x]  Create a new branch dev from the main branch
> * [x]  Commit your changes to the dev branch
> * [x]  Now raise a PR from dev to main
> * [x]  Merge that PR
> 
> Your changes would be visible in Feedback#1 PR and there folks will review it

Thank you for your swift response.
I would sincerely appreciate your guidance on locating the private repository as I have been unable to find it thus far. I have looked for it on both my GitHub Classroom and personal GitHub account, as well as on DiveHQ's account, I have not been successful in locating the repository.
Thank you once again for your attention and support.
image

**Pull request closed without merging**
